[[control]]
name = 'steer_pitch'
control_change = [1, 74]
value = 0.5
range = [0, 1]

[[control]]
name = 'steer_density'
control_change = [2, 75]
value = 0.5
range = [0, 1]

[[control]]
name = 'steer_rate'
control_change = [3, 76]
value = 0.5
range = [0, 1]

[[control]]
name = 'timing_temp'
control_change = [78]
value = 0.2
range = [0, 1]

[[control]]
name = 'rhythm_temp'
control_change = [79]
value = 0.9
range = [0, 1]

[[action]]
name = 'reset'
control_change = [4, 77]

[[action]]
name = 'query'

[[action]]
name = 'mute'

[[preset]]
name = "demo"
channel.1 = {mode="input", inst=1, mute=false}
channel.2 = {mode="auto", inst=113, mute=false}
channel.3 = {mode="auto", inst=114, mute=false}
channel.4 = {mode="auto", inst=12}
channel.5 = {mode="auto", inst=29}
channel.6 = {mode="auto", inst=35}
channel.7 = {mode="auto", inst=19}
channel.8 = {mode="auto", inst=74}
channel.9 = {mode="auto", inst=89}
channel.10 = {mode="input", inst=161, mute=false}
channel.11 = {mode="auto", inst=97}
channel.12 = {mode="auto", inst=109}
channel.13 = {mode="auto", inst=14}
channel.14 = {mode="auto", inst=69}
channel.15 = {mode="auto", inst=82}
channel.16 = {mode="auto", inst=40}

[[preset]]
name = "ens1"
channel.1 = {mode="auto", inst=29, mute=false}
channel.2 = {mode="follow", inst=7, source=1, transpose=[3,15]}
channel.3 = {mode="follow", inst=12, source=2, transpose=[12,24]}
channel.4 = {mode="follow", inst=13, source=3, transpose=[-15,-3]}
channel.5 = {mode="follow", inst=33, source=4, transpose=[-36,-12]}
channel.6 = {mode="follow", inst=10, source=5}
channel.7 = {mode="follow", inst=60, source=6, transpose=[12,36]}
channel.8 = {mode="follow", inst=74, source=7, transpose=[24,36]}
channel.9 = {mode="follow", inst=109, source=8, transpose=[3,7]}
channel.10 = {mode="follow", inst=129, source=9}
channel.11 = {mode="follow", inst=122, source=10}
channel.12 = {mode="follow", inst=48, source=11}  
channel.13 = {mode="follow", inst=78, source=12, transpose=[7,12]}  
channel.14 = {mode="follow", inst=93, source=13, transpose=[12,24]}  
channel.15 = {mode="follow", inst=21, source=14, transpose=[0,4]}  
channel.16 = {mode="follow", inst=16, source=15}

[[preset]]
name = "strings"
channel.1 = {mode="input", inst=7, mute=false}
channel.2 = {mode="auto", inst=41, range=[55,103]}
channel.3 = {mode="auto", inst=42, range=[48,91]}
channel.4 = {mode="auto", inst=43, range=[36,76]}
channel.5 = {mode="auto", inst=44, range=[28,67]}

[[preset]]
name = "brass"
channel.1 = {mode="input", inst=5, mute=false}
channel.2 = {mode="auto", inst=57, range=[55,82]}
channel.3 = {mode="auto", inst=58, range=[40,72]}
channel.4 = {mode="auto", inst=59, range=[28,58]}
channel.5 = {mode="auto", inst=61, range=[34,77]}

[[preset]]
name = "fx"
channel.1 = {mode="input", inst=122, mute=false}
channel.2 = {mode="auto", inst=114}
channel.3 = {mode="auto", inst=119}
channel.4 = {mode="auto", inst=100}
channel.5 = {mode="auto", inst=56}
channel.6 = {mode="auto", inst=102}
channel.7 = {mode="auto", inst=103}
channel.8 = {mode="auto", inst=104}
channel.9 = {mode="auto", inst=121}
channel.10 = {mode="auto", inst=97}
channel.11 = {mode="auto", inst=123}
channel.12 = {mode="auto", inst=124}
channel.13 = {mode="auto", inst=125}
channel.14 = {mode="auto", inst=126}
channel.15 = {mode="auto", inst=127}
channel.16 = {mode="auto", inst=128}

[[preset]]
name = "drums"
channel.1 = {mode="auto", inst=129, mute=false}
channel.2 = {mode="auto", inst=137}
channel.3 = {mode="auto", inst=145}
channel.4 = {mode="auto", inst=153}
channel.5 = {mode="auto", inst=161}
channel.6 = {mode="auto", inst=169}
channel.7 = {mode="auto", inst=177}
channel.8 = {mode="auto", inst=185}
channel.9 = {mode="auto", inst=113}
channel.10 = {mode="auto", inst=114}
channel.11 = {mode="auto", inst=116}
channel.12 = {mode="auto", inst=117}
channel.13 = {mode="auto", inst=118}
channel.14 = {mode="auto", inst=119}
channel.15 = {mode="auto", inst=120}
channel.16 = {mode="auto", inst=48}