# CUSTOMISE:

site_name: notochord
repo_url: https://github.com/Intelligent-Instruments-Lab/notochord
repo_name: iil/notochord

# ONLY CUSTOMISE IF NEEDED:

theme:
  name: "material"
  logo: assets/logo/iil_logo_black.svg
  favicon: assets/favicon/favicon.ico
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.select

copyright: ©️ Intelligent Instruments Lab
extra:
  generator: false
  social:
    - icon: material/link
      link: https://iil.is
      name: Intelligent Instruments Lab
    - icon: material/email-outline
      link: mailto:iil@lhi.is
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/intelligentinstrumentslab
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/intelligentinstruments
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/_iil_is
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@IntelligentInstruments
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fY9GYMebtJ
    - icon: fontawesome/brands/github
      link: https://github.com/intelligent-instruments-lab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/intelligent-instruments-lab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

plugins:
  - search  
  - mkdocstrings
  - include-markdown
  - autorefs
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py  
